server:
  port: 80


spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 100MB
      enabled: true

  mail:
    # qq
    host: smtp.qq.com
    port: 25
    username: 2582025269@qq.com
    password: laoffohuwzdodifa
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false








